name: Tests PHP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Instalar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Instalar dependencias
        run: composer install --no-interaction --prefer-dist

      - name: Ejecutar tests
        run: composer test
